In [2]:
import numpy as np
import matplotlib.pyplot as plt

1. 创建一个一维数组

In [4]:
n1 = np.array([1, 2, 3], dtype="int32")
n1.shape

(3,)

2. 创建一个多维数组

In [6]:
n2 = np.array([[1, 2], [3, 4]])
n2

array([[1, 2],
       [3, 4]])

3. Numpy的数组与Python传统列表有什么区别

1. ndarray 创建的时候就分配了固定的内存大小，若改变大小，相当于销毁当前对象，新建一个并重新分配内存大小
2. ndarray 每个元素都必须是同一类型，若存在多种不同类型，则会自动往内存占用空间大的类型转型，类型转换优先级: 字符串 > 浮点型 > 整型
3. numpy 更适合大量的高级数学运算，相比原生Python代码，精简了许多计算代码，写更少的代码，就能获取更多的算力

4. 将外部的一张图片读取加载到numpy数组中，然后尝试改变数组元素的数值查看对原始图片的影响

In [3]:
n4 = plt.imread("../../../image/d1.jpeg")
n4

array([[[229, 223, 211],
        [227, 221, 207],
        [207, 201, 187],
        ...,
        [223, 217, 205],
        [184, 177, 167],
        [222, 215, 207]],

       [[212, 206, 194],
        [219, 213, 199],
        [216, 210, 196],
        ...,
        [228, 222, 210],
        [210, 203, 193],
        [225, 218, 210]],

       [[215, 209, 197],
        [225, 219, 207],
        [222, 216, 202],
        ...,
        [210, 204, 192],
        [203, 197, 185],
        [221, 214, 204]],

       ...,

       [[215, 209, 195],
        [220, 214, 200],
        [223, 217, 203],
        ...,
        [228, 221, 211],
        [225, 218, 208],
        [231, 224, 214]],

       [[218, 212, 198],
        [217, 211, 197],
        [219, 213, 199],
        ...,
        [228, 222, 210],
        [228, 221, 211],
        [233, 226, 216]],

       [[199, 193, 179],
        [208, 202, 188],
        [222, 216, 202],
        ...,
        [221, 215, 203],
        [225, 219, 207],
        [225, 219, 207]]

5. 分别使用 `linespace` & `arrange` 创建一个等差数列

6. 创建一个0~100的5行4列随机整型数组

7. numpy 常用属性使用

8. 创建一个 `size=(5, 6)` 的随机数组，取出第1,3,5行数据

9. 创建一个 `size=(5, 6)` 的随机数组，切出前两行数据

10. 创建一个 `size=(5, 6)` 的随机数组，切出前两列数据

11. 创建一个 `size=(5, 6)` 的随机数组，切出前两行的前两列数据

12. 创建一个 `size=(5, 6)` 的随机数组，将数组的行倒置

13. 创建一个 `size=(5, 6)` 的随机数组，将数组的列倒置

14. 创建一个 `size=(5, 6)` 的随机数组，将数组行、列都倒置

15. 将一张图片进行左右、上下翻转

16. 将一张图片进行裁剪

17. 将一个5行6列的二维数组，变形为1维数组；再将1维数组转为3行10列

18. 级联操作：将多个numpy数组进行横向或纵向拼接。(特殊场景：行列个数不一样)

19. 级联操作场景应用：将多张图片拼接在一起

20. 创建一个 `size=(5, 6)` 的随机数组，分别求出每一行、每一列的sum、max

21. 计算标准差、方差

22. 计算数组中元素最大值与最小值的差

23. 矩阵转置

In [9]:
arr23 = np.random.randint(0, 100, (5,6))
print(arr23)
print(arr23.T)

[[97 11 40  1 90 25]
 [77 63 90 23 47 36]
 [94 64 79 86 16 74]
 [59 23 61 92 34 35]
 [88 19 47 98 35 88]]
[[97 77 94 59 88]
 [11 63 64 23 19]
 [40 90 79 61 47]
 [ 1 23 86 92 98]
 [90 47 16 34 35]
 [25 36 74 35 88]]


24. 矩阵相乘

In [10]:
np.dot(arr23, arr23.T)

array([[19856, 16915, 16358, 12443, 16073],
       [16915, 22032, 23774, 16456, 19270],
       [16358, 23774, 32301, 22883, 28701],
       [12443, 16456, 22883, 18576, 21782],
       [16073, 19270, 28701, 21782, 28887]])